name = "PhotoOrganizer"
uuid = "364877dc-a3fe-11e8-36b1-6bc00cc37783"
authors = ["Glen Hertz <glen.hertz@gmail.com>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
